# Generated by Django 4.2.3 on 2023-09-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_log_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='reg',
            old_name='Username',
            new_name='username',
        ),
    ]
